AWSTemplateFormatVersion: '2010-09-09'
Description: 'TeAI - AIによる開発支援プラットフォーム'

Parameters:
  InstanceType:
    Description: EC2インスタンスタイプ
    Type: String
    Default: t3a.large
    AllowedValues:
      - t3.medium
      - t3.large
      - t3a.large
      - t3a.xlarge
      - m5.large
      - m5.xlarge
    ConstraintDescription: 有効なEC2インスタンスタイプを指定してください。

  KeyName:
    Description: EC2インスタンスへのSSHアクセスに使用するキーペア名
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: 既存のEC2キーペア名を指定してください。

  VolumeSize:
    Description: EBSボリュームのサイズ（GB）
    Type: Number
    Default: 30
    MinValue: 20
    MaxValue: 100
    ConstraintDescription: 20から100の間の値を指定してください。

  SSHLocation:
    Description: SSHアクセスを許可するIPアドレス範囲
    Type: String
    Default: 0.0.0.0/0
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: CIDR形式で指定してください（例: 203.0.113.0/24）。

Resources:
  TeAISecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: TeAI Security Group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref SSHLocation
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0

  TeAIInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      SecurityGroups:
        - !Ref TeAISecurityGroup
      KeyName: !Ref KeyName
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", AMI]
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeType: gp2
            VolumeSize: !Ref VolumeSize
            DeleteOnTermination: true
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1

          # システムの更新
          yum update -y
          amazon-linux-extras install docker -y
          systemctl enable docker
          systemctl start docker

          # TeAIイメージのプル
          docker pull teai/app:latest
          docker pull teai/runtime:latest

          # TeAIコンテナの起動
          docker run -d --rm \
            -e SANDBOX_RUNTIME_CONTAINER_IMAGE=teai/runtime:latest \
            -e LOG_ALL_EVENTS=true \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v /root/.teai-state:/.teai-state \
            -p 3000:3000 \
            --add-host host.docker.internal:host-gateway \
            --name teai-app \
            teai/app:latest

          # 起動完了のマーク
          touch /tmp/teai_setup_complete

      Tags:
        - Key: Name
          Value: TeAI

Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-0c02fb55956c7d316
    us-east-2:
      AMI: ami-05d72852800cbf29e
    us-west-1:
      AMI: ami-04a50faf2a2ec1901
    us-west-2:
      AMI: ami-0ceecbb0f30a902a6
    eu-west-1:
      AMI: ami-020db2c14939a8efb
    eu-central-1:
      AMI: ami-0a1ee2fb28fe05df3
    ap-northeast-1:
      AMI: ami-0218d08a1f9dac831
    ap-northeast-2:
      AMI: ami-0fd0765afb77bcca7
    ap-southeast-1:
      AMI: ami-0b89f7b3f054b957e
    ap-southeast-2:
      AMI: ami-055166f8a46e33f64
    ap-south-1:
      AMI: ami-0912f71e06545ad88

Outputs:
  InstanceId:
    Description: TeAIインスタンスのID
    Value: !Ref TeAIInstance

  PublicDNS:
    Description: TeAIインスタンスのパブリックDNS
    Value: !GetAtt TeAIInstance.PublicDnsName

  PublicIP:
    Description: TeAIインスタンスのパブリックIP
    Value: !GetAtt TeAIInstance.PublicIp

  TeAIURL:
    Description: TeAIへのアクセスURL
    Value: !Sub http://${TeAIInstance.PublicDnsName}:3000