name: Test

on:
  pull_request:
    branches:
      - develop
      - staging
      - main
    paths:
      - 'deployment/aws/**'
      - '.github/workflows/**'
  push:
    branches:
      - develop
      - staging
    paths:
      - 'deployment/aws/**'
      - '.github/workflows/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          cd deployment/aws/lambda
          npm install
          cd ../../aws/test
          npm install
          
      - name: Run tests
        run: |
          cd deployment/aws/test
          npm test
          
      - name: Validate CloudFormation template
        run: |
          cd deployment/aws
          aws cloudformation validate-template --template-body file://cloudformation.yaml